version: '3'
services:

    db:      
      image: postgres
      environment:
        POSTGRES_PASSWORD: password123
      ports:
        - "5432:5432"        
      volumes:
        - pgdata_jenkins:/var/lib/postgresql/data/
                                
    api:
      build: ./api
      restart: always
      command: python manage.py runserver 0.0.0.0:8000
      ports:
        - "8002:8000"
      volumes:
        - api_data:/docker_api
        - jenkins_data:/var/jenkins_home
      depends_on:
        - db
                
    jenkins:
          build: ./jenkins
          restart: always
          ports:
              - "8080:8080"
              - "50000:50000"
          volumes:            
              - jenkins_data:/var/jenkins_home
volumes:
    api_data:
    jenkins_data:
    pgdata_jenkins:
      